// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimLinkHub.Data;

#nullable disable

namespace SimLinkHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("DeviceConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoConnect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaudRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComPort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configs", (string)null);
                });

            modelBuilder.Entity("SimLinkHub.Models.ArduinoDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("I2CAddress")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Arduinos");
                });

            modelBuilder.Entity("SimLinkHub.Models.SimInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArduinoDeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("InputMax")
                        .HasColumnType("REAL");

                    b.Property<double>("InputMin")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsInverted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("OutputMax")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("OutputMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PinType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SignalPin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SimVarName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<char>("TelemetryPrefix")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArduinoDeviceId");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("SimLinkHub.Models.SimInstrument", b =>
                {
                    b.HasOne("SimLinkHub.Models.ArduinoDevice", "Arduino")
                        .WithMany()
                        .HasForeignKey("ArduinoDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arduino");
                });
#pragma warning restore 612, 618
        }
    }
}
